### PR TITLE
{tools}[foss/2015b] pigz 2.3.3 (REVIEW)

### PR DESCRIPTION
**Pull request by nathanhaigh**
Working on Easyconfigs for pigz-2.3.3-foss-2015b

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e911d8f8e6b3b90ea629 for a full test report.

**Comment by boegel** [comment]
Build fails with:

```
pigz.o:pigz.c:function single_compress: error: undefined reference to 'deflatePending'
```

Wrong zlib version?

**Comment by nathanhaigh** [comment]
According to the author of pigz and zlib, it should work with zlib 1.2.8: https://github.com/madler/pigz/issues/15

**Comment by nathanhaigh** [comment]
Test report by @nathanhaigh
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux ubuntu 14.04, Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz, Python 2.7.6
See https://gist.github.com/964c582b70786a305d8a for a full test report.

**Comment by boegel** [comment]
@nathanhaigh: the test system I submitted the test report from has zlib 1.2.3, so it seems like the zlib provided via EB is not being picked up?

**Comment by nathanhaigh** [comment]
Test report by @nathanhaigh
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux ubuntu 14.04, Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz, Python 2.7.6
See https://gist.github.com/9e2e3d96ec8f25e0ab91 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d691f92eff7e7d4b7a26 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @nathanhaigh!
