### ISSUE TITLE
OpenMPI-2.0.1-gcccuda-2016.10.eb not seeing hwloc

### ISSUE THREAD

**Issue by jhein32** [hpcugent/easybuild-easyconfigs#3828]
Hi, 

I am trying to build OpenMPI-2.0.1-gcccuda-2016.10.eb with EB 3.0.0, using hierarchical modules which minimal toolchains enabled (no dummies though). 

It can't find the hwloc defined as a pre-requisite.  The --robot install of that OpenMPI created a module

`modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44/hwloc/1.11.4.lua`

A --dry-run now reports the hwloc to be there, but the actual build can't find it.  If I understand the logs from the failed build correctly:

`== 2016-11-18 13:44:38,456 build_log.py:149 ERROR EasyBuild crashed with an error (at easybuild/software/Core/EasyBuild/3.0.0/lib/python2.7/site-pac
kages/vsc_base-2.5.5-py2.7.egg/vsc/utils/exceptions.py:124 in __init__): Changing environment as dictated by module failed: name 'false' is not defi
ned (stdout: os.environ["LMOD_DEFAULT_MODULEPATH"] = "/sw/easybuild/modules/all/Core:/sw/easybuild/modules/all:/sw/Modules/modulefiles/Core:/sw/lpkg
/Linux:/sw/lpkg/Core:/sw/lmod/lmod/modulefiles/Core";
os.environ["MODULEPATH"] = "/sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44-GCC-5.4.0-2.26:/sw/easybuild/modules/all/Compiler/GCC/5.4.
0-2.26:/sw/easybuild/modules/all/Compiler/GCCcore/5.4.0:/sw/easybuild/modules/all/Core:/sw/easybuild/modules/all:/sw/Modules/modulefiles/Core:/sw/lp
kg/Linux:/sw/lpkg/Core:/sw/lmod/lmod/modulefiles/Core";`

It is looking for a module:
`/sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44-GCC-5.4.0-2.26/hwloc/1.11.4.lua`

which does not exist (the directory /sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44-GCC-5.4.0-2.26/ exists, but it is empty).

Looking into the configs, I couldn't see an obvious place for the "mismatch" in GCC-CUDA version.

Best wishes
  Joachim

**Comment by boegel** [comment]
@jhein32 hmm, this may be a bug in `HierarchicalMNS` introduced in #1986... It's strange that `--dry-run` *is* seeing the module though.

Can you provide the output of `--dry-run` (which will show the split between short and full name for `hwloc`)?

**Comment by boegel** [comment]
@jhein32 Are you using the `HierarchicalMNS` included with EasyBuild v3.0 directly, without modifications, or did you customise it?

I did a quick try to reproduce the problem using `eb OpenMPI-2.0.1-gcccuda-2016.10.eb --module-naming-scheme HierarchicalMNS --installpath-modules /tmp/modules --module-only -dfr`, but that worked fine...

Can you provide a full debug log?

**Comment by jhein32** [comment]
@boegel sorry for the silence, I was buried in teaching and administration.  The issue is still there in EB 3.0.1.  Just checked for this.  I sent you a message with the requested information to your email.  Let me know if you need more.

**Comment by boegel** [comment]
@jhein32 Can you share the contents of the `Compiler/GCC/5.4.0-2.26/CUDA/8.0.44-GCC-5.4.0-2.26` and `Core/gcccuda/2016.10` module files?

From what I can tell, there is a wrong `module use` (or `prepend-path MODULEPATH`) statement in the `CUDA` module file...

It should be prepending `$MODULEPATH` with `/sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44`, but it's prepending with `/sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44-GCC-5.4.0-2.26` instead.

That explains why the `hwloc` module, which is in the right place, is not found.

Was the `CUDA` module installed with an older version of EasyBuild (pre-3.x)?

**Comment by jhein32** [comment]
Hi Kenneth,

Thanks for getting back.  The files you request look as follows:

```
[hein@aurora1 ~]$ more /sw/easybuild/modules/all/Compiler/GCC/5.4.0-2.26/CUDA/8.0.44-GCC-5.4.0-2.26.lua 
help([[CUDA (formerly Compute Unified Device Architecture) is a parallel
 computing platform and programming model created by NVIDIA and implemented by the
 graphics processing units (GPUs) that they produce. CUDA gives developers access
 to the virtual instruction set and memory of the parallel computational elements in CUDA GPUs. - Homepage: https://developer.nvid
ia.com/cuda-toolkit]])

whatis([[Description: CUDA (formerly Compute Unified Device Architecture) is a parallel
 computing platform and programming model created by NVIDIA and implemented by the
 graphics processing units (GPUs) that they produce. CUDA gives developers access
 to the virtual instruction set and memory of the parallel computational elements in CUDA GPUs. - Homepage: https://developer.nvid
ia.com/cuda-toolkit]])

local root = "/sw/easybuild/software/Compiler/GCC/5.4.0-2.26/CUDA/8.0.44-GCC-5.4.0-2.26"

conflict("CUDA")

if not isloaded("GCCcore/5.4.0") then
    load("GCCcore/5.4.0")
end

if not isloaded("binutils/2.26") then
    load("binutils/2.26")
end
prepend_path("MODULEPATH", "/sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44-GCC-5.4.0-2.26")

prepend_path("CPATH", pathJoin(root, "include"))
prepend_path("CUDA_HOME", root)
prepend_path("CUDA_PATH", root)
prepend_path("LD_LIBRARY_PATH", pathJoin(root, "lib64"))
prepend_path("LIBRARY_PATH", pathJoin(root, "lib64"))
prepend_path("PATH", pathJoin(root, "bin"))
setenv("EBROOTCUDA", root)
setenv("EBVERSIONCUDA", "8.0.44")
setenv("EBDEVELCUDA", pathJoin(root, "easybuild/Compiler-GCC-5.4.0-2.26-CUDA-8.0.44-GCC-5.4.0-2.26-easybuild-devel"))

prepend_path("PATH", root)
-- Built with EasyBuild version 3.0.0
```

```[hein@aurora1 ~]$ more /sw/easybuild/modules/all/Core/gcccuda/2016.10.lua 
help([[GNU Compiler Collection (GCC) based compiler toolchain, along with CUDA toolkit. - Homepage: (none)]])

whatis([[Description: GNU Compiler Collection (GCC) based compiler toolchain, along with CUDA toolkit. - Homepage: (none)]])

local root = "/sw/easybuild/software/Core/gcccuda/2016.10"

conflict("gcccuda")

if not isloaded("GCC/5.4.0-2.26") then
    load("GCC/5.4.0-2.26")
end

if not isloaded("CUDA/8.0.44-GCC-5.4.0-2.26") then
    load("CUDA/8.0.44-GCC-5.4.0-2.26")
end

setenv("EBROOTGCCCUDA", root)
setenv("EBVERSIONGCCCUDA", "2016.10")
setenv("EBDEVELGCCCUDA", pathJoin(root, "easybuild/Core-gcccuda-2016.10-easybuild-devel"))

-- Built with EasyBuild version 3.0.0
```

They were both build with EB 3.0.0 and I don't think I manually changed anything (haven't hacked any lua yet).

So it seems the issue sits in the CUDA module.  Is it worthwhile to force rebuild this with EB 3.0.1?

J.

**Comment by jhein32** [comment]
I rebuild with EB 3.0.1 but the issue persists:

```
-bash-4.2$  more /sw/easybuild/modules/all/Compiler/GCC/5.4.0-2.26/CUDA/8.0.44-GCC-5.4.0-2.26.lua 
help([[CUDA (formerly Compute Unified Device Architecture) is a parallel
 computing platform and programming model created by NVIDIA and implemented by the
 graphics processing units (GPUs) that they produce. CUDA gives developers access
 to the virtual instruction set and memory of the parallel computational elements in CUDA GPUs. - Homepage: https://developer.nvidia.com/cuda
-toolkit]])

whatis([[Description: CUDA (formerly Compute Unified Device Architecture) is a parallel
 computing platform and programming model created by NVIDIA and implemented by the
 graphics processing units (GPUs) that they produce. CUDA gives developers access
 to the virtual instruction set and memory of the parallel computational elements in CUDA GPUs. - Homepage: https://developer.nvidia.com/cuda
-toolkit]])

local root = "/sw/easybuild/software/Compiler/GCC/5.4.0-2.26/CUDA/8.0.44-GCC-5.4.0-2.26"

conflict("CUDA")

if not isloaded("GCCcore/5.4.0") then
    load("GCCcore/5.4.0")
end

if not isloaded("binutils/2.26") then
    load("binutils/2.26")
end
prepend_path("MODULEPATH", "/sw/easybuild/modules/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44-GCC-5.4.0-2.26")

prepend_path("CPATH", pathJoin(root, "include"))
prepend_path("CUDA_HOME", root)
prepend_path("CUDA_PATH", root)
prepend_path("LD_LIBRARY_PATH", pathJoin(root, "lib64"))
prepend_path("LIBRARY_PATH", pathJoin(root, "lib64"))
prepend_path("PATH", pathJoin(root, "bin"))
setenv("EBROOTCUDA", root)
setenv("EBVERSIONCUDA", "8.0.44")
setenv("EBDEVELCUDA", pathJoin(root, "easybuild/Compiler-GCC-5.4.0-2.26-CUDA-8.0.44-GCC-5.4.0-2.26-easybuild-devel"))

prepend_path("PATH", root)
-- Built with EasyBuild version 3.0.1
```

**Comment by boegel** [comment]
@jhein32 I can't seem to reproduce your problem with EasyBuild v3.0.1, I get this in the CUDA module file (i.e. what it should be):

```
prepend_path("MODULEPATH", "/tmp/issue3828/all/Compiler/GCC-CUDA/5.4.0-2.26-8.0.44")
```

So, a few questions:

* Are you using the `CUDA-8.0.44-GCC-5.4.0-2.26.eb` easyconfig that is included in EasyBuild v3.0.x?
* Are you using `HierarchicalMNS` as it is included in EasyBuild v3.0.x, or did you make any local modifications (especially to the `det_modpath_extensions` method)?
The MD5 checksum for `easybuild/tools/module_naming_scheme/hierarchical_mns.py` in your installation should be `694eb0fa5972046987359b25f66d249a`
* We have a test in the framework that verifies the `$MODULEPATH` extensions generated by `HierarchicalMNS`, can you try running that test in your installation? As follows:
```shell
python -O -m test.framework.module_generator test_hierarchical_mns
```

**Comment by jhein32** [comment]
Oh well, that is sort of embarrassing - there was indeed an old CUDA-8.0.44-GCC-5.4.0-2.26.eb in our local stuff.  Though rebuilding that didn't resolve everything.  I also needed to force-rebuild the gcccuda.  Now OpenMPI builds but fails a sanity check - still picking up the wrong hwloc location.  

I see two ways forward:

- We close this now and I get back (mailing list, new issue) if I don't manage to sort me
- We let this hanging open and I get back or close depending on whether or not I get myself sorted.

Please let me know which you prefer - otherwise the ball is with me right now.

Thanks again for your time and apologies for not spotting the issue myself :(

**Comment by boegel** [comment]
@jhein32 It's OK to leave this open until we have fully resolved this.

How is the `CUDA-8.0.44-GCC-5.4.0-2.26.eb` easyconfig that you were using different than the one included in EasyBuild v3.x? I find it strange that it makes a difference...

Are you 100% sure you are using the `HierarchicalMNS` as it is included in EasyBuild v3.x? Using an old/patched copy of `hierarchical_mns.py` is my main suspect for this whole issue...

Did you try to run the unit test as I mentioned? What was the result?

Can you share a debug log for the failing OpenMPI sanity check? How exactly is it still picking up the wrong `hwloc` location? That sounds very weird to me...

**Comment by jhein32** [comment]
Hi @boegel 

It seems that the failed build attempts with the local **CUDA-8.0.44-GCC-5.4.0-2.26.eb** polluted a number of modules.  I force rebuild everything and now it works.  

I still have a debug log from a failed attempt - I am going to email it.  If you think this is important, please ask questions  - I still have the "rotten" CUDA.eb and will attach that as well.  If you like to close this now, please do.

**Comment by boegel** [comment]
@jhein32 Thanks for following this up.

The problem can indeed by explained by the faulty CUDA easyconfig you were using, which basically has this:

```python
name = 'CUDA'
version = '8.0.44'
versionsuffix = '-GCC-5.4.0-2.26'
toolchain = {'name': 'GCC', 'version': '5.4.0-2.26'}
```

The problem is the `versionsuffix`, it should not be there, since you're basically manually replicating the name of the `toolchain` in the `versionsuffix`.
It explains where the extra `-GCC-5.4.0-2.26` in the `$MODULEPATH` extension is coming from, it was basically appending the `versionsuffix`...

Actually, it is the name of the easyconfig file that is wrong... It should be named `CUDA-8.0.44-GCC-5.4.0-2.26-GCC-5.4.0-2.26.eb`. By giving it the wrong name, you're (accidentally) tricking the robot in picking up this CUDA easyconfig.

There's a safeguard for this in the dependency resolution mechanism (more specifically, in the `resolve_dependencies` function in `easybuild/tools/robot.py`, see the code block that spits out the `"does not contain module"` error message), which checks whether a found easyconfig file really matches what it's expected to provide based on the name of the easyconfig file, but it is not working for in this situation.

The problem is probably that `HierarchicalMNS` always requires parsed easyconfig to determine the full module name, because `moduleclass` is required (to discriminate between compiler/MPI/other), and thus the module name is never really determined solely by the dependency specification (which only provides `name`, `version`, `versionsuffix` and `toolchain`); instead, an easyconfig file is located that *seems* to match the dependency spec (based on the name of the easyconfig), which is then used to construct the module name. This basically bypasses the safeguard that checks whether a found easyconfig really provides what is expected, so that's a bug that should be fixed.

cc @ocaisa, @geimer

**Comment by boegel** [comment]
Let's follow this up in https://github.com/hpcugent/easybuild-framework/issues/2049.

@jhein32 I'll leave it up to you whether or not we can close this; are all your questions answered?

**Comment by jhein32** [comment]
Hi Kenneth,

Thanks, so we got at least something - a proper bug identified - out of this, which will help EB.  As I noted my build issues are now resolved, so I close this now.  

Thanks again for your support in this.

Joachim
